name: archive
on:
  workflow_dispatch:
  schedule:
    # every 9:31 JST on 1st day of months
    - cron: '31 0 1 * *'
jobs:
  archive:
    permissions:
      # Required for google-github-actions/auth@v1
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.19.0'
      - uses: actions/checkout@v3
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/ikedam/locations/global/workloadIdentityPools/github-actions/providers/slackarchiver
          service_account: slackarchiver@ikedam.iam.gserviceaccount.com
      - name: archive
        run: go run .
        env:
          TZ: JST
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN}}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
